"""Provides a custom logging handler to redirect log messages to the Tkinter UI.

This module contains the `UIMessageHandler`, a custom class that inherits from
`logging.Handler`. Its purpose is to act as a "pipe" or "bridge" between
Python's standard logging system and the application's graphical user interface.
When this handler is added to the root logger, any log message generated by the
application will be caught and redirected to the UI's dashboard for display.
"""
import logging

from auto_apply.adapters.primary.gui.dashboard import Dashboard as GUIDashboard


class UIMessageHandler(logging.Handler):
    """A custom logging handler that sends log records to a UI dashboard widget.

    This handler is initialized with an instance of the `Dashboard`. When it
    receives a log record via its `emit` method, it formats the record into a
    string and calls the dashboard's `log_message` method to display it to the user.
    """

    def __init__(self, dashboard: GUIDashboard):
        """Initializes the UI message handler.

        Args:
            dashboard: An instantiated `Dashboard` widget that has a `log_message`
                method for displaying messages.
        """
        super().__init__()
        self.dashboard = dashboard

    def emit(self, record: logging.LogRecord) -> None:
        """Processes a log record and sends it to the dashboard.

        This method is automatically called by the Python logging system whenever
        a new log message is generated that meets the handler's level. It
        formats the log record into a string and passes it to the dashboard.

        Args:
            record: The `LogRecord` object generated by the logging call.
        """
        msg = self.format(record)
        self.dashboard.log_message(msg)